//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************

(function () {
    angular
	.module('app')
	.factory('usersFactory', ['$http', function($http) {

    var urlBase = '/api/users';
    var usersFactory = {};

		
		usersFactory.put = function (request) {
        var operation= $http({method: 'PUT', url: urlBase, params: request });
		return operation.then(function(data, status, headers, config) {
            return data.data;
        }, function(error) {
		    console.log(error);
            return  { isOk: false, message: error };
        });
		
    };

		


		usersFactory.delete = function (request) {
        var operation= $http({method: 'DELETE', url: urlBase, params: request });
		return operation.then(function(data, status, headers, config) {
            return data.data;
        }, function(error) {
		    console.log(error);
            return  { isOk: false, message: error };
        });
		
    };

		


		usersFactory.get = function (request) {
        var operation= $http({method: 'GET', url: urlBase, params: request });
		return operation.then(function(data, status, headers, config) {
            return data.data;
        }, function(error) {
		    console.log(error);
            return  { isOk: false, message: error };
        });
		
    };

		


		usersFactory.post = function (request) {
        var operation= $http({method: 'POST', url: urlBase, params: request });
		return operation.then(function(data, status, headers, config) {
            return data.data;
        }, function(error) {
		    console.log(error);
            return  { isOk: false, message: error };
        });
		
    };

		

	return usersFactory;
}]);
}())
