
//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Voodoo;
namespace RunAsWrapper.Core.Controllers
{
	public class AppsController : ApiController
	{
		
		[HttpPut]
		public Voodoo.Messages.Response Put
			([FromUri] RunAsWrapper.Core.Operations.Apps.AppMessage request)
			{
				var op = new RunAsWrapper.Core.Operations.Apps.AppAddCommand(request);
				var response = op.Execute();
				return response;
			}


		[HttpPost]
		public Voodoo.Messages.Response Post
			([FromUri] RunAsWrapper.Core.Operations.Apps.AppMessage request)
			{
				var op = new RunAsWrapper.Core.Operations.Apps.AppUpdateCommand(request);
				var response = op.Execute();
				return response;
			}


		[HttpDelete]
		public Voodoo.Messages.Response Delete
			([FromUri] RunAsWrapper.Core.Operations.Apps.AppMessage request)
			{
				var op = new RunAsWrapper.Core.Operations.Apps.AppDeleteCommand(request);
				var response = op.Execute();
				return response;
			}


		[HttpGet]
		public Voodoo.Messages.PagedResponse<RunAsWrapper.Core.Operations.Apps.AppMessage> Get
			([FromUri] RunAsWrapper.Core.Operations.Apps.AppQueryRequest request)
			{
				var op = new RunAsWrapper.Core.Operations.Apps.AppQuery(request);
				var response = op.Execute();
				return response;
			}

	}
}
